services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data-postgres:/data/postgres
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    ports:
      - "8088:80"
    volumes:
      - data-pgadmin:/root/.pgadmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  data-postgres:
    driver: local
  data-pgadmin:
    driver: local